config/routes.rb
Rails.application.routes.draw do

  root 'developers#index'
  resources :projects
  resources :developers
  resources :time_entries
  resources :sessions

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#logout'

end

app/models/developer.rb
class Developer < ActiveRecord::Base
has_secure_password
has_many :time_entries

validates :name, presence: true
validates :email, presence: true, uniqueness: true
validates :password, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :time_entries
  validates :name, presence: true
  validates :max_hours, presence: true


  def hour_count
    entries = self.time_entries
    entries.reduce(0) do |sum, e|
      sum + e.duration
    end
  end
end

# <%= c.label :developer_id %>
# <%= c.number_field :developer_id %>

app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
  belongs_to :project
  belongs_to :developer
  validates :developer_id, presence: true
  validates :project_id, presence: true
  validates :duration, presence: true
  validates :worked_on, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def authenticate_user
    if session[:developer_id]
      @current_developer = Developer.find_by_id(session[:developer_id])
      return true
    else
      flash[:notice] = "You must log in to see that page"
      redirect_to login_path
      return false
    end
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: [:edit, :update, :destroy]
  before_action :authenticate_user, except: [:new, :create]

  def create
    @developer = Developer.new(developer_params)
    if @developer.save
      respond_to do |format|
        format.html { redirect_to(developers_path, notice: 'User was successfully created.') }
      end
    else
      render :new
    end
  end

  def index
    @developers = Developer.all
  end

  def new
    @developer = Developer.new
  end

  def edit
    @developer = Developer.find(params[:id])
  end

  def show

  end

  def update
    if @developer.update(developer_params)
      redirect_to developers_path, notice: 'Developer was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @developer.destroy
    redirect_to developers_url, notice: 'Developer was successfully destroyed'
  end

  private

  def set_developer
    @developer = Developer.find_by(session[:developer_id])
  end

  def developer_params
    params.require(:developer).permit(:name, :email, :password)
  end

  def make_session(developer)
    session[:developer_id] = developer.id
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user
  def create
    @projects = Project.new(project_params)
    respond_to do |format|
      if @projects.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def show
    # @project = Project.find(params[:id])
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: 'Project successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully removed.'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :max_hours)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    developer = Developer.find_by(email: params[:email])
    if developer && developer.authenticate(params[:password])
      make_session(developer)
      redirect_to projects_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def logout
    session[:developer_id] = nil
    @current_developer = nil
    redirect_to new_session_path
  end

  private

  def make_session(developer)
    session[:developer_id] = developer.id
  end

end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :set_time_entry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user

  def create
    @time_entry = TimeEntry.new(time_entry_params)
    respond_to do |format|
      if @time_entry.save
        format.html { redirect_to time_entries_path, notice: "Time entry successfully created"}
      else
        format.html { render :new }
      end
    end
  end

  def index
    @time_entries = TimeEntry.all
  end

  def new
    @time_entry = TimeEntry.new
  end

  def edit
    @time_entry = TimeEntry.find(params[:id])
  end

  def show
  end

  def update
    respond_to do |format|
      if @time_entry.update(time_entry_params)
        format.html { redirect_to time_entries_path, notice: 'Time entry successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @time_entry.destroy
    redirect_to time_entries_url, notice: 'Time entry was successfully removed.'
  end

  private

  def set_time_entry
    @time_entry = TimeEntry.find(params[:id])
  end

  def time_entry_params
    params.require(:time_entry).permit(:developer_id, :project_id, :duration, :worked_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(developer)
    session[:developer_id] = developer.id
  end

  def current_user
    @current_user ||= Developer.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/views/developers/_form.html.erb
<h2>Create developer</h2>
<% if @developer.errors.any? %>
<div id="error_explanation">
  <h2>Developer cannot be created</h2>
  <ul>
    <% @developer.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for @developer do |c| %>
<div class="field">
  <%= c.label :name %>
  <%= c.text_field :name %>
</div>

<div class="field">
  <%= c.label :email %>
  <%= c.text_field :email %>
</div>

<div class="field">
  <%= c.label :password %>
  <%= c.text_field :password %>
</div>
<%= c.submit "Create developer" %>
<% end %>

app/views/developers/create.html.erb
<h1>Developers#create</h1>
<p>Find me in app/views/developers/create.html.erb</p>

app/views/developers/destroy.html.erb
<h1>Developers#destroy</h1>
<p>Find me in app/views/developers/destroy.html.erb</p>

app/views/developers/edit.html.erb
<h1>Developers#edit</h1>
<p>Find me in app/views/developers/edit.html.erb</p>

<h1>Edit Developer</h1>

<%= render 'form' %>

app/views/developers/index.html.erb
<% if notice %>
<p id="notice"> <%= notice %></p>
<% end %>


<h1>Listing developers</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>

  <tbody>
    <% @developers.each do |dev| %>
      <tr>
        <td><%= dev.name %></td>
        <td><%= dev.email %></td>

        <td><%= link_to 'Edit', edit_developer_path(dev) %></td>
        <td><%= link_to 'Delete', dev, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<td><%= link_to 'New Developer', new_developer_path %></td>
<td><%= link_to 'New Project', new_project_path %></td>
<td><%= link_to 'New Time Entry', new_time_entry_path %></td>

<%= link_to "Logout", login_path %>

app/views/developers/new.html.erb
<h1> New Developer </h1>
<%= render 'form' %>

<%= link_to 'Back', developers_path %>

app/views/developers/show.html.erb
<h1>Developers#show</h1>
<p>Find me in app/views/developers/show.html.erb</p>

app/views/developers/update.html.erb
<h1>Developers#update</h1>
<p>Find me in app/views/developers/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Time Entry</title>
  <%= stylesheet_link_tag 'application', media: 'all'  %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |c| %>
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2>project cannot be created</h2>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


  <div class="field">
    <%= c.label :name %>
    <%= c.text_field :name %>
  </div>

  <div class="field">
    <%= c.label :max_hours %>
    <%= c.number_field :max_hours %>
  </div>

  <div class="actions">
    <%= c.submit "Create project" %>
  </div>
<% end %>

<%= link_to "logout", logout_path %>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

<h1>Edit Project</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<% if notice %>
<p id="notice"> <%= notice %></p>
<% end %>



<h1>Listing Projects</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Max Hours Allowed</th>
    <th>Total Hours Worked</th>
  </tr>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.max_hours %></td>
        <td><%= project.hour_count %></td>

        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<td><%= link_to 'New Project', new_project_path %></td>
<td><%= link_to 'New Developer', new_developer_path %></td>
<td><%= link_to 'New Time Entry', new_time_entry_path %></td>

<%= link_to "logout", logout_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/time_entries/_form.html.erb
<%= form_for @time_entry do |c| %>
<% if @time_entry.errors.any? %>
    <div id="error_explanation">
      <h2>Time entry cannot be created</h2>
    <ul>
      <% @time_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <h2>Create Time Entry</h2>
  <div class="field">
    <%= c.label :developer_id %>
    <%= c.collection_select(:developer_id, Developer.all, :id, :name )%>
  </div>

  <div class="field">
    <%= c.label :project_id %>
    <%= c.collection_select(:project_id, Project.all, :id, :name )%>
  </div>
  <div class="field">
    <%= c.label :duration %>
    <%= c.number_field :duration %>
  </div>

  <div class="field">
    <%= c.label :worked_on %>
    <%= c.date_field :worked_on %>
  </div>

  <div class="actions">
    <%= c.submit "Create Time Entry" %>
  </div>
<% end %>

<%= link_to "logout", logout_path %>

app/views/time_entries/create.html.erb
<h1>TimeEntries#create</h1>
<p>Find me in app/views/time_entries/create.html.erb</p>

app/views/time_entries/destroy.html.erb
<h1>TimeEntries#destroy</h1>
<p>Find me in app/views/time_entries/destroy.html.erb</p>

app/views/time_entries/edit.html.erb
<h1>Edit Time Entry<h1>

<%= render 'form' %>

app/views/time_entries/index.html.erb
<% if notice %>
<p id="notice"> <%= notice %></p>
<% end %>

<h1>Listing Time Entries</h1>
<table class="table table-bordered">
  <tr>
    <th>Developer</th>
    <th>Project</th>
    <th>Duration</th>
    <th>Worked On</th>
  </tr>
  <tbody>
    <% @time_entries.each do |time| %>
      <tr>
        <td><%= time.developer.name %></td>
        <td><%= time.project.name %></td>
        <td><%= time.duration %></td>
        <td><%= time.worked_on %></td>
        <td><%= link_to 'Edit', edit_time_entry_path(time) %></td>
        <td><%= link_to 'Delete', time, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<td><%= link_to 'New Time Entry', new_time_entry_path %></td>
<td><%= link_to 'New Project', new_project_path %></td>
<td><%= link_to 'New Developer', new_developer_path %></td>

<%= link_to "logout", logout_path %>

app/views/time_entries/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', time_entries_path %>

app/views/time_entries/show.html.erb
<h1>TimeEntries#show</h1>
<p>Find me in app/views/time_entries/show.html.erb</p>